### ISSUE TITLE
WoWthing

### ISSUE THREAD

**Issue by Shaker5585** [ThingEngineering/wowthing-again#1254]
Hello! Is anyone else having issues with WoWthing not updating character info? not matter how many times i log off and back onto characters info isn't updating.

**Comment by madcowfred** [comment]
- Are you uploading the addon data? WoWthing checks characters very infrequently otherwise.
- If you are, are you sure the addon is enabled? WoW really likes to randomly disable my addons for me :|

**Comment by powerhandlar** [comment]
,e's having the same problem, I use the WoWsync think client for upload

**Comment by JourneyOver** [comment]
If you guys are talking about the remix specific items and such not updating correctly to show that you have them or not, you need to login to specific classes to actually update those. So like for example if you buy an ensemble that says `Appearances only usable by Evokers, Hunters, and Shaman.` then you need to login to a evoker, hunter or shaman to make the set update. It's the same deal with the trading weapons ensembles as well as the heirlooms (you'll need to login to a class that can use that type of heirloom for it to update)

**Comment by powerhandlar** [comment]
I was talking about all my regular char's, they have not been updated since Remix started.
For example a paladin waring gear 504 meanwhile still shows as 495 - and so on.

**Comment by JourneyOver** [comment]
Hmm I've not had that issue myself personally but as mentioned by madcow I'd one make sure the wowthing addon is actually enabled and two as a last resort delete the `WoWthing_Collector` savedvariable files from your WTF folder created from the addon and then login to each of your toons and see if it fixes anything as sometimes savedvariables can become semi-corrupted due to changes in the addon (this goes for tons of different addons) and will sometimes need to be deleted and remade.

Also make sure that if you are using the wowthing sync client, that the Folder path and API is correct and that it is actually uploading the data.

**Comment by powerhandlar** [comment]
I'm using wowthing sync client 0.6.3
I have:
- deleted WTF\[Account]\SavedVariables\WoWthing_Collector.lua and .lua.bak
- restartet wowthing sync client
- logged into wow
- done something
- logged out
- checked upload log of client ("Upload successful")
- checked website - still wrong itemlevel
- triggered "Manual Upload"
- checked website - still wrong itemlevel
- logged out and in again on website - still wrong itemlevel

What _is_ getting updated is gold, location - but item level equipped of retail chars is not been updated since approx. Remix start. Remix chars _do_ get updated.

Maybe something's incorrect collected by the client? Equipment section of the char (should be 503/504) within lua file as now shows:
```
["equipment"] = {
[24] = "1:193493:13:0:365:3:0:8843,8842,8806::28_2164,38_7,40_340",
[25] = "1:193544:13:0:372:3:0:8843,8842,8807::28_2164,38_8,40_438",
[26] = "1:191232:13:0:358:3:0:8843,8842,8805::28_2164,38_6,40_139",
[27] = "1:193545:13:0:358:3:0:8843,8842,8805::28_2164,38_6,40_439",
[28] = "1:198226:13:0:372:3:0:8843,8842,8807::28_2164,38_8,40_569",
[20] = "1:194875:13:0:372:3:0:8843,8842,8807::28_2164,29_80,38_8,40_683",
[21] = "1:193040:13:0:358:3:0:8843,8842,8805::28_2164,38_6,40_280",
[22] = "1:193039:13:0:372:3:0:8843,8842,8807::28_2164,38_8,40_279",
[23] = "1:191231:13:0:365:3:0:8843,8842,8806::28_2164,29_75,38_7,40_137",
},
```

**Comment by madcowfred** [comment]
That sounds like you might not have a current version of the addon - it changed in v10.2.7.1 to check all equipment slots, those slot numbers are only profession items.

There's also an item level calculation bug that is much more obvious with Remix characters, it doesn't take completely empty slots into account properly so they'll be off until you have neck/rings/trinkets.

**Comment by powerhandlar** [comment]
That does not seem to be true, as I did not update any addmins nor the client - and after it was not udating in the morning, updates surprisingly happend now in the evening without any changes in the versions. It's a surprise and I cannot tell, what happend since, but it was not happening at my end.

**Comment by madcowfred** [comment]
Yes, I made a change to the backend to re-enable equipment via the API, it will use that data if the addon data (more comprehensive) isn't provided. You should still update the addon :)

**Comment by JourneyOver** [comment]
> You should still update the addon

I second this, if you want quicker updates for your characters then it would be a good suggestion to make sure that you keep the addon up to date (the sync client does not download nor update the addon, you'll need to use curseforge client or something like wowup to do so)

Honestly this goes for pretty much any and all addons, gotta update them every so often at least otherwise things tend to break or not work as expected eventually.

**Comment by powerhandlar** [comment]
Shame on me - I was under the impression, that my CurseForge client would have updated it but for some reason it was not integrated there. Due to your insiting suggestions I realised that now, so I reinstalled it into my CurseForge environment and therefore the AddOn should now be updated automatically :)
Thank's for your support and more fore your great work, it is so much helpful to me.

**Comment by powerhandlar** [comment]
And to confirm finally: Updated AddOn and using sync client led to updated item level after next level increase ;)
So it definitely work's.

**Comment by PlemonsBrett** [comment]
Just wanted to bump this issue, probably not exactly the same as the one experienced above.
I do have the most current version of the addon, I just installed it yesterday, but it doesn't pick up any of my Remix characters. I try pressing the "Refresh Character List" button but after loading for a moment, I get the default nginx 404 page, or I get a 501 due to some issue in the redirect.
