### ISSUE TITLE
Earthen icon

### ISSUE THREAD

**Issue by Sooleawa** [ThingEngineering/wowthing-again#1356]
![image](https://github.com/user-attachments/assets/ac8bfa08-49a1-4313-a584-9966efaef8cb)
Earthen race icon missing.
(left bottom questionmark)

Thank You

**Comment by SoulCookie** [comment]
Collecting some links so that future-Freddie doesn't need to:

- Earthen (Horde)
https://www.wowhead.com/race=84/earthen
- Earthen (Alliance)
https://www.wowhead.com/race=85/earthen
- ...from which I downloaded these racial icons:
![race_earthendwarf_female](https://github.com/user-attachments/assets/ab3753b3-4893-41dc-b69f-fe3e071ba8e3)
![race_earthendwarf_male](https://github.com/user-attachments/assets/bfdb27ec-2681-4437-b8a8-c9d3216dbad4)

**Comment by madcowfred** [comment]
Finally extracted this to add it
