### ISSUE TITLE
Never implemented collection things listed on website

### ISSUE THREAD

**Issue by XirevGH** [ThingEngineering/wowthing-again#189]
First of all, great website, love it already, saw it mentioned in the Unity discord!

At a quick glance I noticed a few things that were never implemented into the game listed on the website, these things are:

- Toys
     - Shadowlands

           Glimmerfly Cocoon
           Shadowlands Mini: Grandmaster Vole
   
    -  Battle for Azeroth

           Silver Gilnean Brooch

   -  Legion

           Waywatcher's Boon
           Magi Focusing Crystal
           Whitewater Tsunami

- Achievements
   -  Expansion Features 
      - Pandaria Scenarios

            [The Temple of Kotmogu]
            [For Display Only]
            [Stay Off the Grass]
            
Then one thing that is implemented but just not tracking correctly I guess:

- Progress

  - Shadowlands

    - Maldraxxus Extra Storylines

          Wasteland Work

**Comment by madcowfred** [comment]
Hiya, thanks for the report! I've added those toys to the skip list, will need to add some extra code to hide achievements. I'm not actually sure what's going on with Wasteland Work - the achievement data points to that quest ID, but the Blizzard API does not say any of my characters have completed that quest... which is funny since I have the achievement. I'll dig into it a bit more and see if I can work out what's going on.

**Comment by madcowfred** [comment]
This is (finally) all fixed now
